apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Work\Docker\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: MONGO_DB_URI
          value: mongodb://mongodb:27017/test
        image: api
        name: micro-users
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
